name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: first_test
      id: first_test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: first_test
        setup-command: ''
        command: node main.js
        input: ''
        expected-output: Welcome to extra class
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FIRST_TEST_RESULTS: "${{steps.first_test.outputs.result}}"
      with:
        runners: first_test
